### ISSUE TITLE
ASDF definition links to wrong repo

### ISSUE THREAD

**Issue by crleblanc** [SeismicData/website#1]
The asdf link on your site points to the "Advanced Scientific Data Format" instead of the "Adaptable Seismic Data Format".  Interestingly the former is an intentional departure from HDF5 so it was pretty confusing to find this site linking to it.

The identical names are unfortunate.

**Comment by ghost** [comment]
Are you sure? I just checked the website and it looks fine.

**Comment by krischer** [comment]
I just fixed it ;-)

We had to clear up some confusions with the other ASDF format but now it should be good. I also put a note on our pages to the other ASDF and submitted PRs so they do the same. This should hopefully solve the problem.
