### ISSUE TITLE
ASDF Paper dx.doi.org link not working

### ISSUE THREAD

**Issue by danauerbach** [SeismicData/website#2]
Hi,

I believe the dx.doi.org server requires **https** and does not respond to http requests.

best,
dan

**Comment by krischer** [comment]
Hi,

thanks for bringing this to our attention. Which browser did you use? I just tested it with a couple and raw HTTP seems to work, e.g. the following links works fine for me: http://dx.doi.org/10.1093/gji/ggw319

Cheers!

Lion

**Comment by danauerbach** [comment]
Interesting... I just tried it from home and didn't have a problem. Wondering if it has something to so with the UCSD library serials subscription. When I access the journal from campus it seems to go through the university subscription service. 

Will check again tomorrow from campus.

FYI: Am using Chrome v55 on OS X 10.10.5.


Cheers,
Dan

Dan Auerbach, Application Developer
Project IDA Data Collection Center, Rm 2120
Institute of Geophysics & Planetary Physics, MS 0225
Scripps Institution of Oceanography, UC San Diego
La Jolla, CA 92093
858-822-0797

**Comment by krischer** [comment]
Great. Let me know. If the HTTPS link works everywhere I'll naturally just change it. Thanks!

**Comment by danauerbach** [comment]
Hi Lion,

Well, it appears that for some reason access dx.doi.org from the university network is unreliable. It seems to never successfully resolve the http request when connected directly to the campus network, though it sometimes resolves when using the VPN. It works reliably when off campus.

https seems to works in all instances.

I have left a message with the library staff here, as well as doi.org <http://doi.org/> to see how/why this is happening. According tot he doi.org <http://doi.org/> documentation, http should work. At this point it is hard to say if this is a particular problem of UCSD, or possibly occurs in other academic environment as well.

I can't think of any reason why changing the url to https would be a problem, but of course it's your decision whether or not to make the change.

Regardless, I'll let you know what I find out.

Cheers,
dan



Dan Auerbach, Application Developer
Project IDA Data Collection Center, Rm 2120
Institute of Geophysics & Planetary Physics, MS 0225
Scripps Institution of Oceanography, UC San Diego
La Jolla, CA 92093
858-822-0797

**Comment by danauerbach** [comment]
So, I think I've gotten to the bottom of this and it doesn't appear that you nee to change the URL. While I was able to reproduce the problem even for the root dx.doi.org URL, it appears the problem is with the UCSD wireless network routing. UCSD has implemented significant upgrades in the wireless network on campus over the past couple of months. The subnets and routing "should have" changed for all wireless devices. However, the old subnets are still active, sort of, and my laptop had maintained an old IP address until I reset my networking earlier this morning. I am now on a new wireless subnet, and the http URL works fine.

While I imagine this could be a problem for some small subset of UCSD users, I think it ends there. It isn't a problem that requires changing the URL. 

I apologize for the false alarm. Closing the issue.

cheers,
dan

**Comment by krischer** [comment]
Works for me :-)



> I apologize for the false alarm. Closing the issue.

No need to apologize. Its always good to double and triple check everything!

**Comment by QuLogic** [comment]
We really should use https links unless it breaks something anyway.

**Comment by krischer** [comment]
You are totally right. I just changed the link to `https`.
